// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using System.Text.Json.Serialization;


namespace Entity;

public partial class Category
{
    [Key]
    [Column("ID")]
    public short Id { get; set; }

    [StringLength(50)]
    public string CategoryName { get; set; }

    [InverseProperty("Category")]
    [JsonIgnore] // כדי למנוע לולאה עם Product
    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}