// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using System.Text.Json.Serialization;


namespace Entity;

public partial class Order
{
    [Key]
    [Column("ORDER_ID")]
    public short OrderId { get; set; }

    [Column("ORDER_DATE", TypeName = "smalldatetime")]
    public DateTime OrderDate { get; set; }

    [Column("ORDER_SUM")]
    public short OrderSum { get; set; }

    [Column("USER_ID")]
    public short? UserId { get; set; }

    [InverseProperty("Order")]
    public virtual ICollection<TheOrderItem> TheOrderItems { get; set; } = new List<TheOrderItem>();

    [ForeignKey("UserId")]
    [InverseProperty("Orders")]
    
    public virtual User User { get; set; }
}