// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using System.Text.Json.Serialization;


namespace Entity;

public partial class Product
{
    [Key]
    [Column("Id")]
    public int Id { get; set; }

    [Column("CategoryId")]
    public int CategoryId { get; set; }

    [StringLength(50)]
    public string ProductName { get; set; }

    [StringLength(50)]
    public string ProductDescription { get; set; }

    public int? Price { get; set; }

    [StringLength(50)]
    public string PathOfPicture { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("Products")]
    public virtual Category Category { get; set; }

    [InverseProperty("Product")]
    [JsonIgnore]
    public virtual ICollection<TheOrderItem> TheOrderItems { get; set; } = new List<TheOrderItem>();
}