// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
namespace Entity;

public partial class User
{

    [Key]
    [Column("ID")]
    public short id { get; set; }

    [Column("userName")]
    [StringLength(50)]
    public string UserName { get; set; }

    [Column("password")]
    [StringLength(50)]
    public string Password { get; set; }

    [Column("firstName")]
    [StringLength(50)]
    public string FirstName { get; set; }

    [Column("lastName")]
    [StringLength(50)]
    public string LastName { get; set; }
}